publishDir = "docs"
baseURL = "https://zhubicen.github.io/"
languageCode = "en-us"
title = "quick start"
theme = "bare" 
[markup]
  defaultMarkdownHandler = "blackfriday"

[params]
mainSections = ["posts"]
author = "阿碧"
email = "zhubicen@gmail.com"
description = 'A Software Engineer'
# Include the author name in the <title> of articles
includeAuthorInTitle = true
disableAttribution = true

# [[params.social]]
# icon = "github-circle"
# url = "https://github.com/zhubicen/"

#[[params.social]]
#icon = "weibo"
#url = "https://weibo.com/u/2278143434"