publishDir = "docs"
baseURL = "https://zhubicen.github.io/"
languageCode = "en-us"
title = "quick start"
theme = "bare" 

[params]
mainSections = ["posts"]
author = "阿碧"
email = "zhubicen@gmail.com"
description = 'C++/golang/Java/JavaScript developer'
# Include the author name in the <title> of articles
includeAuthorInTitle = true
